### ISSUE TITLE
Poetry [build-system] is left intact

### ISSUE THREAD

**Issue by gwennlbh** [PacificGilly/poetry_to_uv#10]
idk if that's the intended behavior since some might've added custom configuration section, but for most we use the default, poetry-generated build-system that can just be replaced with `tool.uv.package = true`:

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
